spring:
  # mysql相关配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url : jdbc:mysql://localhost:3306/test_blog?autoReconnect=true&useUnicode=true&characterEncoding=utf-8
    username: root
    password: sqlpw

# 打印sql
logging:
  level:
    cn.mycookies.dao : debug